name: Build
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  linux:
    name: Build Linux G++
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev libglew-dev
      - name: build AntiVim
        run: |
          make build
  macos:
    name: Build MacOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: brew install sdl2 pkg-config glew
      - name: build AntiVim
        run: |
          make build